#DataBase
spring.datasource.url=jdbc:postgresql://localhost:5432/OrderCraft_DB
spring.datasource.username=admin_db
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none

server.servlet.context-path=/api
spring.jpa.show-sql=true

